# Use postgres/example user/password credentials
version: '3.1'

services:
  db:    
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: student
      POSTGRES_USER: student
      POSTGRES_DB: etsy-dock

  etsy-images:
    image: trevorold/etsy-product-images:latest
    restart: always
    environment:
      DB_USER: student
      DB_PASS: student
      DB_NAME: etsy-dock
      DB_HOST: postgres://student:student@db:5432/etsy-dock
      PORT: 8001
    ports:
    - 8001:8001
  
  etsy-summary:
    image: superhsu/etsy-product-summay:latest
    restart: always
    environment:
      DB_HOST: postgres://student:student@db:5432/etsy-dock
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; npm start'

  etsy-proxy:
    image: trevorold/trevor-proxy-server:latest
    restart: always
    ports:
     - 5432:5432
     - 80:80
     - 8000:8000
     - 3000:3000
    